### PR TITLE
Added all missing Text information frames

### PR DESCRIPTION
**Pull request by arpitdhamane**
*Provide a general summary of your changes*
Add all the missing frames contained in 4.2. Text information frames of the ID3 standard.

## Description
All the frame contained in the section quoted above have the same structure of the basic title/subtitle etc. frame. All this frame are implemented using ID3FrameWithStringContent.

> add frame identifiers configuration
> add parsing and creator classes for each frame

## Motivation and Context
*Why is this change required? What problem does it solve? If it fixes an open issue, please link to the issue here.*
#50 

## How Has This Been Tested?
Unit test and CI

## Types of changes
- [x] Enhancement

## Checklist:
- [x] My code follows the code style of this project :beers:.
- [x] My change requires a change to the documentation :bulb: and I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/chicio/ID3TagEditor/blob/master/CONTRIBUTING.md) document :busts_in_silhouette:.
- [x] I have added tests to cover my changes :tada:.
- [x] All new and existing tests passed :white_check_mark:.

### CODE REVIEW

**Comment by chicio** [comment]
Hi @arpitdhamane , thanks for your contribution. Are you planning to work on this feature? Are you blocked in some way? Do you need any help?

ps remember to support my work by ⭐️starring⭐️ the repository

**Comment by chicio** [comment]
FYI: I'm going to merge a big refactoring on master in a few moments. Align your branch/fork before going on with the development.

**Comment by arpitdhamane** [comment]
Okay.
Yes I will check the branch for conflicts.
What else is remaining in the issue. I was under the impression that this task is done.
Can you explain the remaining changes.

**Comment by chicio** [comment]
Hi @arpitdhamane, first of all there are swiftlint issue (check the CI👷and the PR messages).

Then I don't see:
- the creators and parsers for the new frames (see for example `ID3AlbumCreator` and `ID3AlbumContentParsingOperation`)
- the new builders methods to set the frame from a library user point of view (see for example `ID32v3TagBuilder`)
- unit tests that verify that the new component above works as expected
- acceptance tests that verify that the new frames works as expected (see `ID3TagEditorWriteReadAcceptanceTest`)

When your done with the development of the stuff above I will review the mr. Thank you again for your contribution, I will wait for your complete PR 🥳.

**Comment by chicio** [comment]
Hi @arpitdhamane ,

so in the end did you decide to work on this stuff? It is a question just to understand gif you will work on this. Can you give me also an estimation on when do you think you will be ready with the feature?

Thanks you so much again for the help and the contribution.

**Comment by chicio** [comment]
Hi @arpitdhamane , any update? I will start to help you by developing this feature next week if you don't want to work on it anymore. Thanks, Fabrizio.

**Pull request closed without merging**
