### PR TITLE
KMP/KMM projects compatibilty.

### PR DESCRIPTION
**Pull request by Shabinder**
*Provide a general summary of your changes*

## Description
Replace `@import Foundation` statement with `#import <Foundation/Foundation.h>`

## Motivation and Context
It lets your Library to be used in Kotlin Multiplatform/Native Projects such as a project of mine: [SpotiFlyer](https://github.com/Shabinder/SpotiFlyer)

## How Has This Been Tested?
All Your Tests Pass , and I can successfully use your Lib after doing the said changes, Thanks for your work.

## Types of changes
- [x] New feature :sparkles: (non-breaking change which adds functionality)
 - Not  a feature per say, instead makes your lib compatible with KMP/KMM projects using c-interop

## Checklist:
- [x] All new and existing tests passed :white_check_mark:.

### CODE REVIEW

**Comment by chicio** [comment]
Hi @Shabinder,

thank you so much for your contribution. I will definitely merge this now (I didn't know about this difference for Kotlin Platform) and I will add you to the contributors section in the README. 
Thank you for your support.

Fabrizio.

**Comment by chicio** [comment]
Version 4.1.2 released 🚀

**Comment by Shabinder** [comment]
@chicio hi , 
now this pod can be imported into KMP , 
but I just figured that KMP bindings are generated using obj-c interop, and being this a pure Swift Module ,

**Comment by chicio** [comment]
To be honest I don't know KMP, but I know Objective-C 😄 Usually (based on what I can rememeber) the bridging headers are create automatically. Does KPM need specific header in a specific forma/direction position? Do you have any documentation we ca refer to?

**Comment by Shabinder** [comment]
>Does KPM need specific header in a specific forma/direction position? Do you have any documentation we can refer to?

>You can also reuse other libraries and frameworks from the iOS ecosystem in your iOS source sets. Kotlin supports interoperability with Objective-C dependencies and **Swift dependencies if their APIs are exported to Objective-C** with the **@objc attribute**. **_Pure Swift dependencies are not yet supported_**.


@chicio refer to this [Link](https://kotlinlang.org/docs/mobile/add-dependencies.html#ios-dependencies)

**Comment by chicio** [comment]
Ok seems that (as I remembered correctly) it's a matter of adding `@objc` to the public api export by ID3TagEditor (https://github.com/chicio/ID3TagEditor/blob/master/Source/ID3TagEditor.swift). The only concern it's about the compatibility with Linux. 
I'm a busy with another project during these days. So @Shabinder can you try to add the annotation to the public apis and test all the demos (check with the CI that the build is still green on all the platforms)?
Thank you.

**Pull request merged**
